name: Build

on:
  pull_request:
    paths:
      - src/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pull_request:
    name: Pull request
    runs-on: ubuntu-slim
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Upload source
        uses: actions/upload-artifact@v6
        with:
          name: XKit Rewritten (#${{ github.event.pull_request.number }})
          path: src/**
  workflow_dispatch:
    name: Workflow dispatch
    runs-on: ubuntu-slim
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Upload source
        uses: actions/upload-artifact@v6
        with:
          name: XKit Rewritten (${{ github.ref_name }} ${{ github.sha }})
          path: src/**
